// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto1_Web2_IF_Lucas.Models;

#nullable disable

namespace Projeto1_Web2_IF_Lucas.Migrations.DbIf
{
    [DbContext(typeof(db_ifContext))]
    [Migration("20260626024655_InitialDbIf")]
    partial class InitialDbIf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbCidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade");

                    b.ToTable("tbCidade");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPaciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Etnia")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FlgAtleta")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FlgGestante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profissao")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("RG");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelCelular")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelComercial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelResidencial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPaciente");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbPaciente_IdCidade");

                    b.ToTable("tbPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPaciente", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany("TbPaciente")
                        .HasForeignKey("IdCidade")
                        .HasConstraintName("FK_tbPaciente_tbCidade");

                    b.Navigation("IdCidadeNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbCidade", b =>
                {
                    b.Navigation("TbPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
