// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto1_Web2_IF_Lucas.Models;

#nullable disable

namespace Projeto1_Web2_IF_Lucas.Migrations.DbIf
{
    [DbContext(typeof(db_ifContext))]
    [Migration("20260626030432_AddProfissionalEntities")]
    partial class AddProfissionalEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbCidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade");

                    b.ToTable("tbCidade");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbContrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPlano")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdContrato");

                    b.HasIndex(new[] { "IdPlano" }, "IX_tbContrato_IdPlano");

                    b.ToTable("tbContrato");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbMedicoPaciente", b =>
                {
                    b.Property<int>("IdMedicoPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdMedico_Paciente");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InformacaoResumida")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMedicoPaciente");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbMedico_Paciente_IdPaciente");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbMedico_Paciente_IdProfissional");

                    b.ToTable("tbMedico_Paciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPaciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Etnia")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FlgAtleta")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FlgGestante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profissao")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("RG");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelCelular")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelComercial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelResidencial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPaciente");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbPaciente_IdCidade");

                    b.ToTable("tbPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPlano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Validade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPlano");

                    b.ToTable("tbPlano");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbProfissional", b =>
                {
                    b.Property<int>("IdProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF");

                    b.Property<string>("CrmCrn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CRM_CRN");

                    b.Property<string>("Ddd1")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("DDD1");

                    b.Property<string>("Ddd2")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("DDD2");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdContrato")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTipoAcesso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTipoProfissional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Telefone1")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone2")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("IdProfissional");

                    b.HasIndex("IdTipoProfissional");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbProfissional_IdCidade");

                    b.HasIndex(new[] { "IdContrato" }, "IX_tbProfissional_IdContrato");

                    b.HasIndex(new[] { "IdTipoAcesso" }, "IX_tbProfissional_IdTipoAcesso");

                    b.ToTable("tbProfissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbTipoProfissional", b =>
                {
                    b.Property<int>("IdTipoProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoProfissional");

                    b.ToTable("tbTipoProfissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbContrato", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbPlano", "IdPlanoNavigation")
                        .WithMany("TbContrato")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbContrato_tbPlano");

                    b.Navigation("IdPlanoNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbMedicoPaciente", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbMedicoPaciente")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbMedico_Paciente_tbPaciente");

                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbMedicoPaciente")
                        .HasForeignKey("IdProfissional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbMedico_Paciente_tbProfissional");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPaciente", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany("TbPaciente")
                        .HasForeignKey("IdCidade")
                        .HasConstraintName("FK_tbPaciente_tbCidade");

                    b.Navigation("IdCidadeNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbProfissional", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbProfissional_tbCidade");

                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbContrato", "IdContratoNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbProfissional_tbContrato");

                    b.HasOne("Projeto1_Web2_IF_Lucas.Models.TbTipoProfissional", "IdTipoProfissionalNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdTipoProfissional")
                        .HasConstraintName("FK_tbProfissional_tbTipoProfissional");

                    b.Navigation("IdCidadeNavigation");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdTipoProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbCidade", b =>
                {
                    b.Navigation("TbPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbContrato", b =>
                {
                    b.Navigation("TbProfissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPaciente", b =>
                {
                    b.Navigation("TbMedicoPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbPlano", b =>
                {
                    b.Navigation("TbContrato");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbProfissional", b =>
                {
                    b.Navigation("TbMedicoPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_Lucas.Models.TbTipoProfissional", b =>
                {
                    b.Navigation("TbProfissional");
                });
#pragma warning restore 612, 618
        }
    }
}
