// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// Lucas Wilman da Silva Crispim
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_Web2_IF_Lucas.Models;

public partial class db_ifContext : DbContext
{
    public db_ifContext(DbContextOptions<db_ifContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TbPaciente> TbPaciente { get; set; }

    public virtual DbSet<TbCidade> TbCidade { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TbPaciente>(entity =>
        {
            entity.HasKey(e => e.IdPaciente);

            entity.HasOne(d => d.IdCidadeNavigation)
                .WithMany(p => p.TbPaciente)
                .HasForeignKey(d => d.IdCidade)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbPaciente_tbCidade");
        });

        modelBuilder.Entity<TbCidade>(entity =>
        {
            entity.HasKey(e => e.IdCidade);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
