// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// Lucas Wilman da Silva Crispim
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_Web2_IF_Lucas.Models;

[Table("tbCidade")]
public partial class TbCidade
{
    [Key]
    public int IdCidade { get; set; }

    public int? IdEstado { get; set; }

    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [InverseProperty("IdCidadeNavigation")]
    public virtual ICollection<TbPaciente> TbPaciente { get; set; } = new List<TbPaciente>();
}
